[package]
name = "guard-cli"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "stellar-upgrade-guard"
path = "src/main.rs"

[dependencies]
clap.workspace = true
guard-core.workspace = true
guard-rpc.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

[dev-dependencies]
stellar-xdr.workspace = true
tempfile = "3.23.0"
